CHANGELOG.md, dashboard/services/expose/views.py, dashboard/templates/stats/downstream.html, dashboard/urls.py, requirements/base.txt, transtats/settings/base.py
=> ping server

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, Makefile, README.md, dashboard/templates/home.html, dashboard/templates/howto.html, dashboard/templates/stats/index.html, dashboard/views.py, docs/source/index.md, setup.py
=> Minor UI Fixes

.travis.yml, CHANGELOG.md, Makefile, README.md, dashboard/managers/base.py, dashboard/managers/inventory.py, dashboard/tests.py, dashboard/tests/test_inventory.py, transtats/settings/base.py, transtats/settings/dev.py, transtats/settings/prod.py, transtats/settings/test.py
Issue https://github.com/transtats/transtats/issues/11
=> add test case and logs

.gitignore, CHANGELOG.md, Dockerfile, Makefile, README.md, Vagrantfile, dashboard/templates/howto.html, deploy/docker/Dockerfile, deploy/docker/conf/sample_keys.json, deploy/docker/launch.sh, devel/ansible/playbook.yml, devel/ansible/roles/setup/tasks/main.yml
=> Fedora Readiness

CHANGELOG.md, dashboard/admin.py, dashboard/constants.py, dashboard/managers/inventory.py, dashboard/managers/jobs.py, dashboard/managers/utilities.py, dashboard/services/consume/config/damnedlies.py, dashboard/services/consume/restclient.py, dashboard/urls.py, dashboard/utilities/xmltodict.py
Initial [DamnedLies](https://wiki.gnome.org/DamnedLies) Integration
=> enable adding gnome packages

CHANGELOG.md, dashboard/templates/settings/packages.html, dashboard/urls.py, dashboard/views.py
Export list of packages to `CSV`.
This resolves issue https://github.com/transtats/transtats/issues/3
=> export packages to CSV

Dockerfile, deploy/docker/Dockerfile, requirements/base.txt, transtats/settings/auth.py, transtats/settings/base.py, transtats/settings/dev.py, transtats/settings/test.py
=> fix auth in test-env

deploy/docker/conf/sample_keys.json
- Docs Pull Request
Issue #XXX
=> Added OIDC_RP_CLIENT_SECRET in sample_key.json

dashboard/tests/test_inventory.py
Adding test cases to increase code coverage of InventoryManager
Issue #77
=> Increase code coverage of InventoryManager class

dashboard/tests/test_inventory.py, dashboard/tests/testdata/db_fixtures.py, dashboard/tests/testdata/mock_values.py, dashboard/tests/testdata/test_data.py
Adds tests for the PackagesManager from `dashboard/managers/inventory.py`
Issue #77
=> Add tests for PackagesManager 

dashboard/urls.py, requirements/base.txt, transtats/__init__.py, transtats/settings/auth.py, transtats/settings/base.py, transtats/settings/dev.py, transtats/urls.py
Changes to support `Django 2.0`
Issue #97 
Depends on https://github.com/mozilla/mozilla-django-oidc/pull/203
Tasks
=> django 2.0 support

CHANGELOG.md, README.md, deploy/docker-compose/docker-compose.yml, deploy/docker-compose/transtats/Dockerfile, deploy/docker-compose/transtats/datadump.json, deploy/docker-compose/transtats/launch.sh, deploy/docker-compose/transtats/sample_keys.json, deploy/docker-compose/transtats/wait-for-it.sh, docs/source/getinvolved.rst, docs/source/index.rst
This uses `wait-for-it.sh` from [vishnubob/wait-for-it](https://github.com/vishnubob/wait-for-it) which is licensed under [MIT](https://github.com/vishnubob/wait-for-it/blob/master/LICENSE)
Issue #102
=> Add docker-compose setup for deployment

Makefile, dashboard/templates/base.html, transtats/node/package-lock.json, transtats/node/package.json, transtats/settings/base.py, transtats/static/css/transtats.css
ui
Some initial work of migrating to PatternFly + JQuery 
- Modify `base.html` 
- Download dependencies via `npm`
- Adds `make ui-deps`
- More information for About modal  
Related issue #28
=> [UI] Initial work of migration to PatternFly 

dashboard/forms.py, dashboard/templates/languages/language_list.html, dashboard/templates/languages/language_new.html, dashboard/templates/languages/language_set_new.html, dashboard/templates/languages/language_set_update.html, dashboard/templates/languages/language_update.html, dashboard/urls.py, dashboard/views.py, transtats/static/css/transtats.css
`ui-base`
Converts following Django admin section to new UI
https://github.com/transtats/transtats/issues/28#issuecomment-374887597
=> [UI] Add languages section 

dashboard/templates/base.html, dashboard/templates/form_base.html, dashboard/templates/languages/language_list.html, dashboard/templates/languages/language_new.html, dashboard/templates/languages/language_set_new.html, dashboard/templates/languages/language_set_update.html, dashboard/templates/languages/language_update.html
`ui-base`
- Adds `form_base.html` other forms will be extended from this one.
- Fixes wrong 'disabled icon' from languages section 
- Updates urls from `base.html`
=> [UI] Add form_base.html and various fixes

.circleci/config.yml, CHANGELOG.md, Dockerfile, dashboard/managers/graphs.py, dashboard/managers/inventory.py, dashboard/managers/resources.py, dashboard/views.py, deploy/docker/Dockerfile
This change fixes branch mapping for `GNOME Packages` with the help of build system.
=> gnome branch mapping

deploy/docker-compose/docker-compose.yml, deploy/docker-compose/transtats/Dockerfile, deploy/docker-compose/transtats/launch.sh, deploy/docker/launch.sh, deploy/openshift/README.md, deploy/openshift/buildconfig.yml, deploy/openshift/deploymentconfig.yml, deploy/openshift/imagestream.yml, deploy/openshift/route.yml, deploy/openshift/secret.yml, deploy/openshift/service.yml
- This modifies the existing Dockerfile of `docker-compose` to use latest fedora image, also makes the Dockerfile to be standalone.
- Adds yml files to `deploy/openshift` for OpenShift deployment  
- Uses Dockerfile source method to build the image
See the commit messages for all the details
=> Add files for OpenShift deployment

dashboard/management/commands/syncpackages.py, dashboard/managers/jobs.py, dashboard/templates/stats/_branch_mapping.html, dashboard/templates/stats/_package_details.html, dashboard/templates/stats/_workload_combined.html, dashboard/templates/stats/trans_status_package.html, dashboard/templates/stats/trans_status_release.html, dashboard/urls.py, dashboard/views.py
=> syncpackages cmd

.circleci/config.yml, CHANGELOG.md, dashboard/converters/specfile.py, dashboard/engine/action_mapper.py, deploy/openshift/deploymentconfig.yml, deploy/openshift/route.yml
=> job improvements

dashboard/engine/action_mapper.py, dashboard/templates/jobs/log_detail.html
=> more bug fixes

CHANGELOG.md, dashboard/admin.py, dashboard/constants.py, dashboard/engine/action_mapper.py, dashboard/engine/parser.py, dashboard/forms.py, dashboard/managers/graphs.py, dashboard/managers/inventory.py, dashboard/managers/packages.py, dashboard/managers/resources.py, dashboard/managers/utilities.py, dashboard/services/consume/config/weblate.py, dashboard/services/consume/restclient.py, dashboard/services/expose/views.py, dashboard/templates/base.html, dashboard/templatetags/custom_tags.py, dashboard/urls.py, requirements/base.txt
[Weblate](https://weblate.org/en/) support in Transtats
Tasks
Issue #170
=> weblate support

Vagrantfile
Fixing permission issue on /workspace
Updated Vagrant file for fixing shared volumes permission issue
Issue #191
=> Updated Vagrant file for fixing shared volumes permission issue

deploy/openshift/README.md
- Docs Pull Request
Adding minishift installation link in README.md file
=> Adding minishift installation link in README.md file

deploy/docker-compose/transtats/launch.sh, deploy/docker/conf/supervisord.conf
Supervisor conf didn't work  well with `f32` base img
this is a quick work around to fix the same!
Issue #XXX
=> set supervisor conf

dashboard/templates/base.html, dashboard/templates/howto.html, dashboard/templates/releases/_outofsync_packages.html, dashboard/templates/releases/_releases_summary.html, dashboard/templates/releases/release_list.html, dashboard/templates/summary.html, dashboard/templatetags/custom_tags.py
Some UI changes on landing page for better logged-in experience!
=> some landing page UI changes

dashboard/managers/graphs.py
=> fix: bug pkg_with_stats_diff stack trace

deploy/docker-compose/transtats/Dockerfile
Added missing system dependency 'python3-pip' to Dockerfile.
=> Add python3-pip system dependency

CHANGELOG.md, Makefile, dashboard/tasks.py, dashboard/templates/geolocation/_territory_summary.html, dashboard/templates/packages/package_delete.html, dashboard/templates/packages/package_list.html, dashboard/urls.py, dashboard/views.py, deploy/docker/conf/transtats_celery.ini, deploy/docker/conf/transtats_celerybeat.ini, transtats/celery.py, transtats/settings/base.py
`periodic_task` has been removed in **Celery 5.0.x** hence moving to `shared_task` !!
=> fix celery

dashboard/templates/coverage/coverage_rule_list.html, dashboard/templates/coverage/coverage_rule_view.html
=> minor ui change

dashboard/managers/pipelines.py, dashboard/services/consume/restclient.py, dashboard/services/resources.py, dashboard/views.py
=> hotfix: unknown disappearing of pipelines

dashboard/managers/pipelines.py, dashboard/templates/ci/_ci_pipeline.html
=> disable toggle visibility in background for the pipelines

dashboard/jobs_framework/action_mapper.py, dashboard/services/resources.py, dashboard/tests/testdata/job-templates/syncdownstream_1.yml
get stats from a scratch build (koji/brew), YML adaptation..
```
job:
name: downstream stats
type: syncdownstream
buildsys: %BUILD_SYSTEM%
exception: raise
execution: sequential
package: %PACKAGE_NAME%
return_type: json
tags:
- %BUILD_TAG%
tasks:
- get:
- name: Task Info
- task_id: %TASK_ID%
- download: SRPM
- unpack: SRPM
- load: Spec file
- unpack: tarball
- apply: patch
- filter:
- name: files
- domain: %PACKAGE_NAME%
- ext: PO
- dir: ''
- calculate: Stats
```
=> sync koji tasks for stats

dashboard/converters/xml2dict.py, dashboard/jobs_framework/action_mapper.py, dashboard/management/commands/initlogin.py, dashboard/management/commands/syncpackages.py, dashboard/managers/graphs.py, dashboard/managers/inventory.py, dashboard/managers/jobs.py, dashboard/managers/packages.py, dashboard/models.py, dashboard/services/expose/views.py, dashboard/templates/ci/pipeline_details_base.html, dashboard/templates/packages/_package_details.html, dashboard/templates/packages/package_list.html, dashboard/templates/platforms/platform_list.html, dashboard/templates/releases/product_release_list.html, dashboard/templatetags/custom_tags.py, dashboard/views.py, transtats/static/js/ie-emulation-modes-warning.js, transtats/urls.py
=> some fixes

dashboard/managers/graphs.py, dashboard/services/expose/views.py, dashboard/templatetags/custom_tags.py
=> some more fixes

dashboard/managers/jobs.py, dashboard/templates/jobs/_job_form.html, dashboard/templatetags/custom_tags.py
=> a few bug fixes

dashboard/jobs_framework/action_mapper.py
=> Add simplify_plural_forms_in_po_header pre-hook

CHANGELOG.md, README.md, dashboard/jobs_framework/action_mapper.py, dashboard/managers/jobs.py, dashboard/views.py
=> Add gem files unpacking support in syncdownstream jobs
